apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: multi-tier-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/Hesham-Elngar/Deploy-a-Multi-Tier-App-with-ArgoCD.git"
    targetRevision: main
    path: base 
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
